name: Build PIXEL OS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    env:
      PACKAGES_PATH: ${{ github.workspace }}\edk2

    steps:

    - name: Checkout PIXEL-OS
      uses: actions/checkout@v4

    - name: Checkout EDK II
      uses: actions/checkout@v4
      with:
        repository: tianocore/edk2
        path: edk2
        submodules: recursive
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Python Requirements
      working-directory: edk2
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r pip-requirements.txt

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build BaseTools
      working-directory: edk2
      run: |
        python BaseTools\Edk2ToolsBuild.py -t VS2022

    - name: Configure EDK II
      working-directory: edk2
      run: |
        call edksetup.bat Rebuild

    - name: Copy PixelBootPkg
      run: |
        xcopy PixelBootPkg edk2\PixelBootPkg /E /I /Y

    - name: Register PixelBoot
      working-directory: edk2
      run: |
        powershell -NoProfile -Command "$p='MdeModulePkg\MdeModulePkg.dsc'; $c=Get-Content $p -Raw; if ($c -notmatch '(?m)^\s*PixelBootPkg/PixelBoot\.inf\s*$') { $c=$c -replace '(?ms)(^\[Components\]\r?\n)', '$1PixelBootPkg/PixelBoot.inf`r`n'; Set-Content -Path $p -Value $c -NoNewline }"

    - name: Build
      working-directory: edk2
      run: |
        call edksetup.bat Rebuild

        build ^
          -a X64 ^
          -b DEBUG ^
          -t VS2022 ^
          -p MdeModulePkg\MdeModulePkg.dsc

    - name: Collect EFI Files
      run: |
        mkdir artifact

        for /r edk2\Build %%f in (*.efi) do (
          echo Found %%f
          copy "%%f" artifact\
        )

    - name: Upload EFI
      uses: actions/upload-artifact@v4
      with:
        name: PIXEL-EFI
        path: artifact
